package edu.progAvUD.segundoTaller2Corte.cliente.vista;

/**
 *
 * @author Cristianlol789
 */
import javax.swing.*;
import java.awt.*;

public class PanelPrivado extends JPanel {

    public JTextArea panMostrar;
    public JTextField txtMensage;
    public JButton butEnviar;
    public JLabel lblAmigo;  // nuevo

    public PanelPrivado() {
        setLayout(new BorderLayout());

        // Etiqueta superior para mostrar el nombre del amigo
        lblAmigo = new JLabel("Chat privado con: ");
        lblAmigo.setHorizontalAlignment(SwingConstants.CENTER);
        add(lblAmigo, BorderLayout.NORTH);

        // Área de mensajes
        panMostrar = new JTextArea();
        panMostrar.setEditable(false);
        JScrollPane scroll = new JScrollPane(panMostrar);
        add(scroll, BorderLayout.CENTER);

        // Parte inferior (escribir mensaje)
        txtMensage = new JTextField(30);
        butEnviar = new JButton("Enviar");

        JPanel panAbajo = new JPanel(new BorderLayout());
        panAbajo.add(new JLabel("  Ingrese mensaje a enviar:"), BorderLayout.NORTH);
        panAbajo.add(txtMensage, BorderLayout.CENTER);
        panAbajo.add(butEnviar, BorderLayout.EAST);

        add(panAbajo, BorderLayout.SOUTH);
    }

    public void setAmigo(String nombre) {
        lblAmigo.setText("Chat privado con: " + nombre);
    }

    // Getters
    public JTextArea getPanMostrar() {
        return panMostrar;
    }

    public JTextField getTxtMensage() {
        return txtMensage;
    }

    public JButton getButEnviar() {
        return butEnviar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setDefaultCloseOperation(int EXIT_ON_CLOSE) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private Container getContentPane() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void pack() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
