package edu.progAvUD.segundoTaller2Corte.cliente.vista;

import java.net.URL;
import javax.swing.BoxLayout;
import javax.swing.JEditorPane;
import javax.swing.JScrollPane;

/**
 *
 * @author Cristianlol789
 */
public class PanelAyuda extends javax.swing.JPanel {

    private JScrollPane scrollPanel;
    private JEditorPane html;
    /**
     * Creates new form PanelAyuda
     */
    public PanelAyuda() {
        html = new JEditorPane();
        html.setEditable(false);
        scrollPanel = new JScrollPane(html);
        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        add(scrollPanel);
        initComponents();
    }

    public void mostrarContenido(URL url) throws Exception{
        html.setPage(url);
        html.setContentType("text/html");
        html.setText("<html><body><h2>Error al cargar la ayuda</h2></body></html>");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
