package edu.progAvUD.segundoTaller2Corte.cliente.vista;

/**
 *
 * @author Cristianlol789
 */
import java.awt.*;
import java.util.Vector;
import javax.swing.*;

public class PanelPrincipal extends JPanel {

    public JTextArea panMostrar;
    public JTextField txtMensage;
    public JButton butEnviar;
    private JLabel lblNomUser;
    public JList lstActivos;
    public JButton butPrivado;

    private JMenuBar barraMenu;
    private JMenu JMAyuda;
    public JMenuItem help;
    private JMenu JMAcerca;
    public JMenuItem acercaD;

    public PanelPrincipal() {
        txtMensage = new JTextField(30);
        butEnviar = new JButton("Enviar");
        lblNomUser = new JLabel("Usuario <<  >>", JLabel.CENTER);

        panMostrar = new JTextArea();
        panMostrar.setColumns(25);
        panMostrar.setEditable(false);
        panMostrar.setForeground(Color.BLUE);
        panMostrar.setBorder(BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(25, 10, 80)));

        lstActivos = new JList();
        butPrivado = new JButton("Privado");

        // Panel inferior (mensaje + botón enviar)
        JPanel panAbajo = new JPanel(new BorderLayout());
        panAbajo.add(new JLabel("Ingrese mensaje a enviar:"), BorderLayout.NORTH);
        panAbajo.add(txtMensage, BorderLayout.CENTER);
        panAbajo.add(butEnviar, BorderLayout.EAST);

        // Panel derecho (usuario + texto + campo escribir)
        JPanel panRight = new JPanel(new BorderLayout());
        panRight.add(lblNomUser, BorderLayout.NORTH);
        panRight.add(new JScrollPane(panMostrar), BorderLayout.CENTER);
        panRight.add(panAbajo, BorderLayout.SOUTH);

        // Panel izquierdo (usuarios activos)
        JPanel panLeft = new JPanel(new BorderLayout());
        panLeft.add(new JScrollPane(lstActivos), BorderLayout.CENTER);
        panLeft.add(butPrivado, BorderLayout.NORTH);

        // Panel dividido horizontalmente
        JSplitPane sldCentral = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, panLeft, panRight);
        sldCentral.setDividerLocation(100);
        sldCentral.setDividerSize(7);
        sldCentral.setOneTouchExpandable(true);

        // Menú
        barraMenu = new JMenuBar();
        JMAyuda = new JMenu("Ayuda");
        help = new JMenuItem("Ayuda");

        JMAcerca = new JMenu("Acerca de");
        acercaD = new JMenuItem("Créditos");

        JMAyuda.add(help);
        JMAcerca.add(acercaD);
        barraMenu.add(JMAcerca);
        barraMenu.add(JMAyuda);

        // Agregar al panel
        setLayout(new BorderLayout());
        add(barraMenu, BorderLayout.NORTH);
        add(sldCentral, BorderLayout.CENTER);
    }

    // New public methods for UI updates

    public void appendMensaje(String mensaje) {
        panMostrar.append(mensaje + "\n");
    }

    public void actualizarListaUsuarios(Vector<String> usuarios) {
        lstActivos.setListData(usuarios);
    }

    public void setNombreUsuario(String nombre) {
        lblNomUser.setText("Usuario " + nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
