package edu.progAvUD.segundoTaller2Corte.cliente.vista;

import edu.progAvUD.segundoTaller2Corte.cliente.control.ControlGrafico;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Cristianlol789
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    //private ControlGrafico controlGrafico;
    public DialogAyuda dialogAyuda;
    public PanelChatCliente panelChatCliente;
    public DialogChatPrivado dialogChatPrivado;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(/*ControlGrafico controlGrafico*/) {
        //this.controlGrafico = controlGrafico;
        initComponents();
    }
    
    public void incializarVentana() throws Exception {
        this.panelChatCliente = new PanelChatCliente();
        this.dialogAyuda = new DialogAyuda();
        this.dialogChatPrivado = new DialogChatPrivado();
    }
    
    /**
     * Muestra un cuadro de diálogo con un mensaje de éxito.
     *
     * @param mensaje Mensaje a mostrar al usuario.
     */
    public void mostrarMensajeExito(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * Muestra un cuadro de diálogo con un mensaje de error.
     *
     * @param mensaje Mensaje a mostrar al usuario.
     */
    public void mostrarMensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    public String darNombreCliente(){
        return JOptionPane.showInputDialog("Introducir Nick :");
    }
    
    public String darIpServidor(){
        return JOptionPane.showInputDialog("Introducir IP_SERVER :", "localhost");
    }

    /**
     * Cambia el panel visible en la ventana principal.
     * Ajusta el tamaño, centra la ventana en pantalla y actualiza la interfaz gráfica.
     *
     * @param panel Panel que se desea mostrar en la ventana principal.
     */
    public void mostrarPanel(JPanel panel) {
        setContentPane(panel);
        pack(); // Ajusta el tamaño de la ventana según el contenido
        setLocationRelativeTo(null); // Centra la ventana en la pantalla
        revalidate(); // Refresca el layout
        repaint(); // Redibuja la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCreditos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemAyuda = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Acerca de");

        jMenuItemCreditos.setText("Creditos");
        jMenu1.add(jMenuItemCreditos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenuItemAyuda.setText("Ayuda");
        jMenu2.add(jMenuItemAyuda);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItemAyuda;
    public javax.swing.JMenuItem jMenuItemCreditos;
    // End of variables declaration//GEN-END:variables
}
