package edu.progAvUD.segundoTaller2Corte.cliente.vista;

import edu.progAvUD.segundoTaller2Corte.cliente.control.ControlGrafico;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Andres Felipe
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private ControlGrafico controlGrafico;
    public PanelPrincipal panelPrincipal;
    public PanelAyuda panelAyuda;
    public PanelPrivado panelPrivado;
    
    public VentanaPrincipal(ControlGrafico controlGrafico) {
        setVisible(true);
        initComponents();
        this.controlGrafico = controlGrafico;
        this.panelPrincipal = new PanelPrincipal();
        this.panelAyuda = new PanelAyuda();
        this.panelPrivado = new PanelPrivado();
    }

    /**
     * Muestra un cuadro de diálogo con un mensaje de éxito.
     *
     * @param mensaje Mensaje a mostrar al usuario.
     */
    public void mostrarMensajeExito(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * Muestra un cuadro de diálogo con un mensaje de error.
     *
     * @param mensaje Mensaje a mostrar al usuario.
     */
    public void mostrarMensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * Cambia el contenido visible de la ventana principal por el panel
     * recibido. Ajusta el tamaño, centra la ventana y refresca la interfaz para
     * reflejar el cambio.
     *
     * @param panel Panel que se desea mostrar en la ventana principal.
     */
    public void mostrarPanel(JPanel panel) {
        setContentPane(panel);
        pack(); // Ajusta el tamaño de la ventana según el contenido
        setLocationRelativeTo(null); // Centra la ventana en la pantalla
        revalidate(); // Refresca el layout
        repaint(); // Redibuja la ventana
    }
    
    public String pedirIPServer(){
        return JOptionPane.showInputDialog("Introducir IP_SERVER :","localhost");
    }
    
    public void mostrarAcera(){
        JOptionPane.showMessageDialog(this, "José Valdez/Javier Vargas", "Desarrollado por", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
